# Generated by Django 5.1.6 on 2025-03-01 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="destination",
            unique_together={("city", "country")},
        ),
    ]
